# kableExtra包画图

记录一些自己可能会常用的表格，至于更多的可以参考大佬们写的教程，真的很酷。

- [中文教程](https://haozhu233.github.io/kableExtra/awesome_table_in_html_cn.html)

- [英文教程](http://haozhu233.github.io/kableExtra/)

```{r}
library(kableExtra)
```

## 生成html表格
```{r}
dt <- mtcars[1:5, 1:6]

kable(dt, "html")
```

## 渲染表格
```{r}
# bootstrap是个开源的CSS库，可以用来很方便地美化HTML页面。
dt %>%
  kable("html") %>%
  kable_styling()
```

- 其他风格
   - striped
   - bordered
   - hover
   - condensed
   - responsive
   
```{r}
# 给表格加上斑马纹和悬浮效果
kable(dt, "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```




```{r}
# 让内容显得更紧凑
kable(dt, "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```



```{r}
# 让表格样式随屏幕宽度变化，更适合手机屏。
kable(dt, "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

```{r}
# 控制表格的宽度
kable(dt, "html") %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```

## 搭配dplyr

```{r message=FALSE, warning=FALSE}
library(dplyr)
mtcars[1:10, 1:2] %>%
  mutate(
    car = row.names(.),
    # You don't need format = "html" if you have ever defined options(knitr.table.format)
    mpg = cell_spec(mpg, "html", color = ifelse(mpg > 20, "red", "blue")),
    cyl = cell_spec(cyl, "html", color = "white", align = "c", angle = 45, 
                    background = factor(cyl, c(4, 6, 8), 
                                        c("#666666", "#999999", "#BBBBBB")))
  ) %>%
  select(car, mpg, cyl) %>%
  kable("html", escape = F) %>%
  kable_styling("striped", full_width = F)
```



## 搭配formattable

```{r}
library(formattable)
mtcars[1:5, 1:4] %>%
  mutate(
    car = row.names(.),
    mpg = color_tile("white", "orange")(mpg),
    cyl = cell_spec(cyl, "html", angle = (1:5)*60, 
                    background = "red", color = "white", align = "center"),
    disp = ifelse(disp > 200,
                  cell_spec(disp, "html", color = "red", bold = T),
                  cell_spec(disp, "html", color = "green", italic = T)),
    hp = color_bar("lightgreen")(hp)
  ) %>%
  select(car, everything()) %>%
  kable("html", escape = F) %>%
  kable_styling("hover", full_width = F) %>%
  column_spec(5, width = "3cm") %>%
  add_header_above(c(" ", "Hello" = 2, "World" = 3))
```

## 列组

```{r}
kable(dt, "html") %>%
  kable_styling("striped") %>%
  add_header_above(c(" " = 1, "Group 1" = 2, "Group 2" = 2, "Group 3" = 2))
```


```{r}
kable(dt, "html") %>%
  kable_styling(c("striped", "bordered")) %>%
  add_header_above(c(" ", "Group 1" = 2, "Group 2" = 2, "Group 3" = 2)) %>%
  add_header_above(c(" ", "Group 4" = 4, "Group 5" = 2)) %>%
  add_header_above(c(" ", "Group 6" = 6))
```



## 行组

```{r}
kable(mtcars[1:10, 1:6], "html", caption = "Group Rows") %>%
  kable_styling("striped", full_width = F) %>%
  group_rows(index = c(" " = 3, "Group 1" = 4, "Group 2" = 3))
```

```{r}
kable(dt, "html") %>%
  kable_styling("striped", full_width = F) %>%
  group_rows("Group 1", 3, 5, label_row_css = "background: repeating-linear-gradient(45deg, #d9230f, #d9230f 10px, #f96352 10px, #f96352 20px); color: #fff;")
```

```{r}
# 行的缩进
kable(dt, "html") %>%
  kable_styling("striped", full_width = F) %>%
  add_indent(c(1, 3, 5))
```
```{r}
# 合并行
collapse_rows_dt <- data.frame(C1 = c(rep("a", 10), rep("b", 5)),
                               C2 = c(rep("c", 7), rep("d", 3), rep("c", 2), rep("d", 3)),
                               C3 = 1:15,
                               C4 = sample(c(0,1), 15, replace = TRUE))
kable(collapse_rows_dt, "html", align = "c") %>%
  kable_styling(full_width = F) %>%
  column_spec(1, bold = T) %>%
  collapse_rows(columns = 1:2)
```


## 保存HTML表格

```{r}
kable(mtcars) %>%
  kable_styling() %>%
  save_kable(file = "tables/table1.html", self_contained = T)
```


